version: "3.8"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: cloud
      POSTGRES_PASSWORD: password
  redis:
    image: redis:5.0.7
    volumes:
      - ./tmp/redis:/var/lib/redis/data
  sidekiq:
    build: .
    volumes:
      - .:/myapp
    command: bundle exec sidekiq
    environment:
      redis_url: redis://redis:6379/12
    depends_on:
      - redis
      - db

  web:
    build: .
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      redis_url: redis://redis:6379/12
      secret: ection_ada
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
